---
title: "Spring 2021 Calendar for 432"
output: 
    html_document:
        toc: true
        toc_float: true
---

## General Comments {-}

- All class sessions are held from **1:00 to 2:15 PM** via Zoom. 
    - Dr. Love opens the sessions 10 minutes early and stays on for 15 minutes (or more, if needed) after class ends to address questions.
- All times listed on this page refer to **US Eastern Time**.
- The Zoom link for each class is [available on Canvas](https://canvas.case.edu) in the Announcements section. Zoom recordings are also posted to [Canvas](https://canvas.case.edu).
- A list of key topics for the course is available on the [site home page](index.html)


## April 2021

LINK | Date | Description
--------: | -------: | :-------------------------------------------------------
[Class 16](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class16) | 04-01 | Regression on Nominal multi-categorical outcomes.
*Reading* | 04-02 | **Silver** Chapter 12.
[Class 17](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class17) | 04-06 | More on ordinal regression models, Time-to-event data, Kaplan-Meier curves
**due** | 04-07 | [Minute Paper](https://github.com/THOMASELOVE/432-2021/tree/master/minutepapers) after Class 17 due at noon.
[Class 18](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class18) | 04-08 | Comparing Survival curves, Fitting Cox proportional hazards models.
*Reading* | 04-09 | **Silver** Chapter 13.
[Class 19](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class19) | 04-13 | Cox models with `cph`, Fitting Robust Linear Models.
**due** | 04-14 | [Minute Paper](https://github.com/THOMASELOVE/432-2021/tree/master/minutepapers) after Class 19 due at noon.
**Focus 1** | 04-15 | [Project 2](https://github.com/THOMASELOVE/432-2021/tree/master/project2) **Focus Day 1**
*Reading* | 04-16 | **Silver** Chapter 11.
**due** | 04-19 | [Project 2 Outline and Scheduling Form](http://bit.ly/432-2021-project2-register) submitted by NOON.
[Class 20](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class20) | 04-20 | Survey Weights in Regression Models, Feature Selection and the Lasso.
**due** | 04-21 | [Minute Paper](https://github.com/THOMASELOVE/432-2021/tree/master/minutepapers) after Class 20 due at noon.
[Class 21](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class21) | 04-22 | An Overly Brief Introduction to Hierarchical Data
[Class 22](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class22) | 04-27 | Retrospective Design / Thinking about Power After the Fact
**Focus 2** | 04-29 | [Project 2](https://github.com/THOMASELOVE/432-2021/tree/master/project2) **Focus Day 2**
*Reading* | 04-30 | **Silver** complete the book if you haven't already.

## May 2021

LINK | Date | Description
--------: | -------: | :-------------------------------------------------------
**due** | 05-03 | [Lab 04](https://github.com/THOMASELOVE/432-2021/tree/master/labs) and [Lab 05](https://github.com/THOMASELOVE/432-2021/tree/master/labs) each due at 9 PM.
**Focus 3** | 05-04 | [Project 2](https://github.com/THOMASELOVE/432-2021/tree/master/project2) **Focus Day 3**
**due** | 05-05 | [Minute Paper](https://github.com/THOMASELOVE/432-2021/tree/master/minutepapers) before Class 23 due at noon.
[Class 23](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class23) | 05-06 | Designing Studies and Visualizations Well: A Look Forward
Quiz B  | 05-07 | [Quiz B](https://github.com/THOMASELOVE/432-2021/tree/master/quizzes/quizB) will be available 05-07 and is due 05-17 at NOON.
**due** | 05-14 | (Optional) [Lab Regrade Request Form](http://bit.ly/432-2021-lab-regrade-requests) due 05-14 at NOON.
**due** | 05-14 | (Optional) [Lab 06](https://github.com/THOMASELOVE/432-2021/tree/master/labs) due 05-14 at NOON.
**due** | 05-14 | Final version of [Project 2](https://github.com/THOMASELOVE/432-2021/tree/master/project2) Data, Portfolio and Presentation Materials also due at NOON.
**due** | 05-17 | [Quiz B](https://github.com/THOMASELOVE/432-2021/tree/master/quizzes/quizB) will be available 05-07 and is due 05-17 at NOON.

## Project 2 Deadlines

Date | Description
---- | -----------------------------------------------------
**04-19** | [Project 2 Outline and Scheduling Form](http://bit.ly/432-2021-project2-register) submitted by NOON.
**04-20** | Dr. Love will announce the schedule for Project 2 Presentations.
TBD | [Project 2](https://github.com/THOMASELOVE/432-2021/tree/master/project2) Live Presentation via Zoom on Apr 29, May 7, 10 or 11.
TBD | Pre-presentation version of [Project 2](https://github.com/THOMASELOVE/432-2021/tree/master/project2) Materials due to Canvas 3 hours before your presentation.
**05-14** | Final version of [Project 2](https://github.com/THOMASELOVE/432-2021/tree/master/project2) Portfolio, Data and Presentation Materials due to Canvas at NOON.

## TA Office Hours

We have eight teaching assistants working with the course this semester, and you can learn more about them in [the Course Syllabus](https://thomaselove.github.io/432-2021-syllabus/teaching-assistants.html).

TA office hours begin on Thursday 2021-02-04 and continue through Monday 2021-05-10. Zoom information to join these sessions is posted to [Canvas](https://canvas.case.edu/) in the **Announcements** section and also in our shared Google Drive (be sure to log in to Google via CWRU to see the shared Drive.)

- Thursdays from 5:00 to 6:30 PM ET
- Fridays from 3:00 to 4:30 PM ET and from 6:00 to 7:30 PM ET
- Saturdays from 10:30 to 11:30 AM ET and from 3:00 to 4:30 PM ET
- Sundays from 9:00 to 10:00 AM ET and from 2:30 to 4:00 PM ET and from 6:30 to 8:00 PM ET
- Mondays from 3:00 to 4:30 PM ET and from 6:30 to 8:00 PM ET

Remember that [Piazza](https://piazza.com/case/spring2021/pqhs432) is available 24 hours a day, 7 days a week for your questions and answers.

## Readings

The two books we're reading this term are:

- Jeff Leek **How to be a modern scientist**, available as an ebook [on Leanpub](https://leanpub.com/modernscientist) for a suggested $10, and abbreviated as **Leek** below. The book is short, and I encourage you to just read it as soon as possible (it won't take more than a couple of hours), then refer to it later in the term as specific issues arise.
- Nate Silver **The Signal and the Noise**, available [on Amazon](https://www.amazon.com/Signal-Noise-Many-Predictions-Fail-but/dp/0143125087) for about $20, and abbreviated as **Silver** below. Some chapters will seem more relevant to you than others, and feel free to skim those in an initial reading. The most useful chapters are the Introduction, Chapters 1-3, 6-8 and 12, according to past students in the course.

The calendar specifies reading dates on Fridays. We expect you to read the material specified over that weekend (before the next class.) We encourage you to read the books in advance of the specified dates. In some cases, you have a choice between chapters of Silver to read at a particular time. We encourage you to return to chapters you didn't choose later in the semester so that by the end of April you've read the entire book.

## Before Class Starts

Once you have registered for the course, please visit our [Welcome to 432 survey](http://bit.ly/432-2021-welcome-survey). You'll need to log into Google via CWRU to take the survey, which should take about 15 minutes to complete. If possible, please complete the survey before our first class on 2021-02-02.

## February 2021

LINK | Date | Description
--------: | -------: | :-------------------------------------------------------
[Class 01](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class01) | 02-02 | Getting Started, Building Table 1.
[Class 02](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class02) | 02-04 | Interaction and ANOVA/ANCOVA models
*Reading* | 02-05 | **Silver** Intro, Chapter 1. **Leek** Data Sharing, Reading scientific papers
**due** | 02-08 | [Lab 01](https://github.com/THOMASELOVE/432-2021/tree/master/labs) due at 9 PM. 
[Class 03](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class03) | 02-09 | Building Non-Linear Terms in Linear Models
**due** | 02-10 | [Minute Paper](https://github.com/THOMASELOVE/432-2021/tree/master/minutepapers) after Class 03 due at noon.
[Class 04](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class04) | 02-11 | Interactions, Splines and Imputation in Linear Models
*Reading* | 02-12 | **Silver** Chapter 2. **Leek** Paper writing, Scientific code
[Class 05](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class05) | 02-16 | Binary Regression Models
**due** | 02-17 | [Minute Paper](https://github.com/THOMASELOVE/432-2021/tree/master/minutepapers) after Class 05 due at noon.
[Class 06](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class06) | 02-18 | Building Models for Binary Outcomes
*Reading* | 02-19 | **Silver** Chapter 3, 4, or 5 (your choice). **Leek** Internal scientific communication, Your online identity
**due** | 02-22 | [Lab 02](https://github.com/THOMASELOVE/432-2021/tree/master/labs) due at 9 PM.
[Class 07](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class07) | 02-23 | Linear Regression with `ols`
**due** | 02-24 | [Minute Paper](https://github.com/THOMASELOVE/432-2021/tree/master/minutepapers) after Class 07 due at noon.
[Class 08](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class08) | 02-25 | Linear Regression and Multiple Imputation with `ols`
*Reading* | 02-26 | Complete **Leek**

## March 2021

LINK | Date | Description
--------: | -------: | :-------------------------------------------------------
**due** | 03-01 | [Project 1 Proposal](https://github.com/THOMASELOVE/432-2021/tree/master/project1) is due at 9 PM.
No class | 03-02 | Dr. Love at AHRQ HCRT.
[Class 09](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class09) | 03-04 | Logistic Regression with `lrm`
*Reading* | 03-05 | **Silver** Chapter 6.
[Class 10](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class10) | 03-09 | More on linear and logistic regressions
**due** | 03-10 | [Minute Paper](https://github.com/THOMASELOVE/432-2021/tree/master/minutepapers) after Class 10 due at noon.
[Class 11](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class11) | 03-11 | More on linear and logistic regressions
*Reading* | 03-12 | **Silver** Chapter 7.
**due** | 03-15 | [Lab 03](https://github.com/THOMASELOVE/432-2021/tree/master/labs) due at 9 PM.
No class | 03-16 | University Break.
[Class 12](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class12) | 03-18 | Multiple Imputation and the `mice` package for `lm` and `glm` fits.
*Reading* | 03-19 | **Silver** Chapter 8.
**due** | 03-22 | [Quiz A](https://github.com/THOMASELOVE/432-2021/tree/master/quizzes/quizA) will be available 03-12 and is due 03-22 at 9 PM.
[Class 13](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class13) | 03-23 | P values and Replicable Research
**due** | 03-24 | [Minute Paper](https://github.com/THOMASELOVE/432-2021/tree/master/minutepapers) after Class 13 due at noon.
[Class 14](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class14) | 03-25 | Regression on Counts
*Reading* | 03-26 | **Silver** Chapter 9 or 10 (your choice).
**due** | 03-29 | [Project 1 Portfolio and Presentation](https://github.com/THOMASELOVE/432-2021/tree/master/project1) are due at 9 PM.
[Class 15](https://github.com/THOMASELOVE/432-2021/tree/master/classes/class15) | 03-30 | Regression on Ordinal multi-categorical outcomes.
