---
title: "Minute Papers"
---

## Where can I find the links to the Minute Papers?

All minute papers are linked through the [Course Calendar](calendar.html). You will need to be logged into Google via your CWRU account in order to complete the minute papers, or review the feedback Dr. Love builds.

The [direct link on Github for 432 Minute Papers is available now](https://github.com/THOMASELOVE/432-2021/tree/master/minutepapers).

## What is a minute paper?

"Minute Papers" are short forms (administered using Google Forms) that allow you to tell us about your experience, summarize some of the things you've learned recently, and (most importantly) ask questions of Dr. Love. 

- Each of these are meant to take less than 10 minutes (in most cases, less than 5 minutes) for you to complete. 
- The Minute Papers form a major part of your class participation grade, and we expect you to complete as many as possible on time. 
- The Minute Papers will be made available on Mondays before their deadline (which is always noon on Wednesday) and Dr. Love will provide extensive feedback on Thursdays in class in response to the Minute Papers which were submitted by the deadline.

## What questions can we expect in a minute paper?

Virtually every minute paper includes the following items:

1. What was the most important thing you learned about in 432 recently?
2. What question would you most like Dr. Love to answer for you at this time?
3. If you'd like to leave a comment for Dr. Love, or ask Dr. Love anything else, here's a place to do that.

In each form, Dr. Love adds several questions (usually short-answer, multiple-choice or ratings) about specific issues related to the course at that time.

There is rarely any preparation required for completing a Minute Paper, and you should complete the Minute Paper even if you've yet to view the most recent class session.
